-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- #######################################################################################

-- AUTOGENERATED HYPRLAND CONFIG.

-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hyprland.conf AND EDIT IT,

-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.

-- #######################################################################################

--autogenerated = 1 # remove this line to remove the warning

-- This is an example Hyprland config file.

-- Refer to the wiki for more information.

-- https://wiki.hyprland.org/Configuring/

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

-- You can split this configuration into multiple files

-- Create your files separately and then link them to this file like this:

-- source = ~/.config/hypr/myColors.conf

--###############

--## MONITORS ###

--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@100",
    position = "0x0",
    scale    = 1,
})

--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use

local terminal = "kitty"

local fileManager = "nemo"

local menu = "rofi -show drun"

-- $wallpapers = wallpapers

-- local ranger = ranger

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:


-- exec-once = qs -c eqsh

hl.on("hyprland.start", function () 
  hl.exec_cmd("systemctl --user start skwd-daemon")
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox") -- Execute waybar, hyprpaper, firefox
end)

--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 10,
        gaps_workspaces = 50,
        border_size = 1,
        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        -- col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
        -- col.inactive_border = rgba(595959aa)
        no_focus_fallback = true,
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = "rgba(0DB7D455)",
            inactive_border = "rgba(31313600)",
        }
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding_power = 2,
        rounding = 18,
        -- Change transparency of focused and unfocused windows
        active_opacity = 0.9,
        inactive_opacity = 0.87,
        shadow = {
            enabled = true,
        -- ignore_window = true
        range = 50,
        offset = "10,4",
        render_power = 10,
        color = "rgba(00000027)"
        },
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            -- enabled = true,
        xray = true,
        special = false,
        new_optimizations = true,
        size = 10,
        passes = 3,
        brightness = 1,
        noise = 0.05,
        contrast = 0.89,
        vibrancy = 0.5,
        vibrancy_darkness = 0.5,
        popups = false,
        popups_ignorealpha = 0.6,
        input_methods = true,
        input_methods_ignorealpha = 0.8
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#animations

hl.config({
  animations = {
    enabled = true,

    -- Curves: { nombre, p1, p2, p3, p4 }
    bezier = {
      { "expressiveFastSpatial", 0.42, 1.67, 0.21, 0.90 },
      { "expressiveSlowSpatial", 0.39, 1.29, 0.35, 0.98 },
      { "expressiveDefaultSpatial", 0.38, 1.21, 0.22, 1.00 },
      { "emphasizedDecel", 0.05, 0.7, 0.1, 1 },
      { "emphasizedAccel", 0.3, 0, 0.8, 0.15 },
      { "standardDecel", 0, 0, 0, 1 },
      { "menu_decel", 0.1, 1, 0, 1 },
      { "menu_accel", 0.52, 0.03, 0.72, 0.08 },
      { "stall", 1, -0.1, 0.7, 0.85 },
    },

    -- Configs: { arbol_o_nombre, habilitado, velocidad, curva, estilo_opcional }
    animation = {
      -- Ventanas
      { "windowsIn", true, 1.5, "emphasizedDecel", "popin 80%" },
      { "fadeIn", true, 1.5, "emphasizedDecel" },
      { "windowsOut", true, 1.2, "emphasizedDecel", "popin 90%" },
      { "fadeOut", true, 1.2, "emphasizedDecel" },
      { "windowsMove", true, 2, "emphasizedDecel", "slide" },
      { "border", true, 5, "emphasizedDecel" },

      -- Capas / Paneles
      { "layersIn", true, 1.5, "emphasizedDecel", "popin 93%" },
      { "layersOut", true, 1.2, "menu_accel", "popin 94%" },

      -- Fundidos
      { "fadeLayersIn", true, 0.5, "menu_decel" },
      { "fadeLayersOut", true, 1.5, "stall" },

      -- Espacios de trabajo (Workspaces)
      { "workspaces", true, 3.5, "menu_decel", "slide" },

      -- Workspaces especiales
      { "specialWorkspaceIn", true, 1.8, "emphasizedDecel", "slidevert" },
      { "specialWorkspaceOut", true, 1.0, "emphasizedAccel", "slidevert" },

      -- Zoom
      { "zoomFactor", true, 1.8, "standardDecel" },
    },
  },
})

-- Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/

-- "Smart gaps" / "No gaps when only"

-- uncomment all if you wish to use that.

-- workspace = w[tv1], gapsout:0, gapsin:0

-- workspace = f[1], gapsout:0, gapsin:0

-- windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]

-- windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]

-- windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]

-- windowrulev2 = rounding 0, floating:0, onworkspace:f[1]

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
  dwindle = {
      force_split                  = 0,
      preserve_split               = false,
      smart_split                  = false,
      smart_resizing               = true,
      permanent_direction_override = false,
      special_scale_factor         = 1,
      split_width_multiplier       = 1.0,
      use_active_for_splits        = true,
      default_split_ratio          = 1.0,
      split_bias                   = 0,
      precise_mouse_move           = false,
  },
})
-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

hl.config({
    master = {
        new_status = "master",
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
    misc = {
        force_default_wallpaper = -1,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false,
        -- If true disables the random hyprland logo / anime girl background. :(
    },
})

--############

--## INPUT ###

--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "us",
        numlock_by_default = true,
        repeat_delay = 250,
        repeat_rate = 35,

        follow_mouse = 1,
        off_window_axis_events = 2,

        touchpad = {
            natural_scroll = false, -- 'yes' cambia a true en Lua
            disable_while_typing = true,
            clickfinger_behavior = true,
            scroll_factor = 0.7
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#gestures

hl.config({
    gestures = {
        -- workspace_swipe = false
    },
})

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

--##################

--## KEYBINDINGS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "A", hl.dsp.exec_cmd("kitty"))

hl.bind(mainMod .. " + " .. "Z", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "M", hl.dsp.exit())

--hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd())

hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("rofi -show drun"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

--hl.bind(mainMod .. " + " .. "J", hl.dsp.layout(nil))

-- dwindle

hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd("local_var_wallpapers"))

-- dwindle

hl.bind(mainMod .. " + " .. "C", hl.dsp.exec_cmd("grim -g $(slurp)-| wl-copy"))

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

-- bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

-- bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

-- bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 5%+

-- bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 5%-

-- Requires playerctl

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule v1

hl.window_rule({
    name  = "float",
    match = {
        class = "^(($terminal))$",
    },
    float = true,
})

-- para que la temrinal aparezca siempre flotante

hl.window_rule({
    name  = "size_800_400",
    match = {
        class = "^(kitty)$",
    },
    size = "800 400",
})

-- Example windowrule v2

-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$ 

-- Ignore maximize requests from apps. You'll probably like this.

hl.window_rule({
    name  = "suppressevent_maximi",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland

hl.window_rule({
    name  = "nofocus",
    match = {
        class = "^$",
        title = "^$",
        xwayland = 1,
        --floating = 1,
        fullscreen = 0,
       -- pinned = 0,
    },
    no_focus = true,
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("swww-daemon")
    hl.exec_cmd("qs -c cwc")
    hl.exec_cmd("qs -c noctalia-shell")
end)
